server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ai-real-estate-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/dblogement?currentSchema=dblogement
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000

openai:
  api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
  api-url: https://api.openai.com/v1/chat/completions
  model: gpt-3.5-turbo

logging:
  level:
    com.realestate: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"